---
scenario:
  name: centos-latest
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    # - lint
    - verify
    - destroy

dependency:
  name: galaxy

driver:
  name: docker
platforms:
  - name: telegraf-centos-latest
    image: redbeard28/docker-centos7-ansible
    pre_build_image: yes
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    published_ports:
#      - 0.0.0.0:6000:22/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    enabled: False

verifier:
  name: goss
  lint:
    name: yamllint
