---
scenario:
  name: ubuntu-16.04
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    # - lint
    - verify
    - destroy

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker

platforms:
  - name: ubuntu-16.04
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: yes
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    published_ports:
#      - 0.0.0.0:6000:22/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    enable: False

verifier:
  name: goss
  lint:
    name: yamllint
